select
    user_id,
    card_index,
    transaction_date,
    transaction_time,
    date(transaction_date)                  as transaction_day,
    extract(year from transaction_date)     as transaction_year,
    extract(month from transaction_date)    as transaction_month,
    amount,
    use_chip,
    merchant_id,
    merchant_city,
    merchant_state,
    merchant_zip,
    mcc,
    is_fraud,
    error_type,
    full_name,
    current_age,
    gender,
    customer_city,
    customer_state,
    yearly_income,
    total_debt,
    fico_score,
    card_brand,
    card_type,
    has_chip,
    credit_limit,
    card_on_dark_web

from {{ ref('int_transactions_enriched') }}
